"""Initial schema

Revision ID: 93c904418457
Revises: 
Create Date: 2026-06-24 22:41:19.729031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c904418457'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_ratings_total', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_attractions_name'), 'attractions', ['name'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_location_name'), 'search_queries', ['location_name'], unique=False)
    op.create_table('search_query_association',
    sa.Column('search_query_id', sa.Uuid(), nullable=False),
    sa.Column('attraction_place_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['attraction_place_id'], ['attractions.place_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_query_id', 'attraction_place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_query_association')
    op.drop_index(op.f('ix_search_queries_location_name'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_attractions_name'), table_name='attractions')
    op.drop_table('attractions')
    # ### end Alembic commands ###
